name: Setup Terraform And Provision

on:
  push:
    branches: [feature/T-3345-terraform-pipeline]
jobs:
  init_and_plan_terraform:
    name: Init And Plan Terraform
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.version.outputs.date }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialise Terraform
        run: |
              cat <<EOF > ~/.aws/config
              [profile terraform-ctwo]
              region = us-east-1
              EOF

              cat <<EOF > ~/.aws/credentials
              [profile terraform-ctwo]
              aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
              EOF

              terraform init
              terraform fmt
              terraform validate
              terraform plan