# Generated by Django 3.0 on 2022-10-30 13:59

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NowSelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_name', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='media/properties')),
                ('property_type', models.CharField(choices=[('None', 'None'), ('Land', 'Land'), ('Buildings', 'Buildings')], default='None', max_length=15)),
                ('info', models.TextField(default='')),
                ('title', models.CharField(blank=True, default='', max_length=80)),
                ('location', models.CharField(default='', max_length=500)),
                ('unit_of_plot', models.PositiveSmallIntegerField(default=0)),
                ('price_per_unit_plot', models.CharField(default='', max_length=15)),
                ('on_promo', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_sold_out', models.BooleanField(default=False)),
                ('promo_price_per_unit_or_plot', models.CharField(blank=True, default='', max_length=15, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_name', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='media/properties')),
                ('video', models.FileField(blank=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='media/properties/videos', validators=[cloudinary_storage.validators.validate_video])),
                ('property_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('property_type', models.CharField(choices=[('None', 'None'), ('Land', 'Land'), ('Buildings', 'Buildings')], default='None', max_length=15)),
                ('location', models.CharField(default='', max_length=500)),
                ('no_of_unit_or_plot', models.PositiveSmallIntegerField(default=0)),
                ('price_per_unit_plot', models.CharField(default='', max_length=15)),
                ('on_promo', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('promo_price_per_unit_or_plot', models.CharField(blank=True, default='', max_length=15, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(default='', max_length=150)),
                ('last_name', models.CharField(default='', max_length=150)),
                ('address', models.CharField(default='', max_length=500)),
                ('state_of_origin', models.CharField(default='', max_length=500)),
                ('account_merchant', models.CharField(default='', max_length=500)),
                ('account_number', models.CharField(default='', max_length=500, unique=True)),
                ('date_of_birth', models.DateField()),
                ('mobile', models.CharField(max_length=13, null=True, unique=True)),
                ('gender', models.CharField(choices=[('None', 'None'), ('Male', 'Male'), ('Female', 'Female')], default='None', max_length=15)),
                ('referral_code', models.CharField(default='', max_length=40, unique=True)),
                ('referral', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('realtor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realtor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoldProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_name', models.CharField(max_length=500)),
                ('property_id', models.CharField(default='', max_length=50)),
                ('property_type', models.CharField(choices=[('None', 'None'), ('Male', 'Male'), ('Female', 'Female')], default='None', max_length=15)),
                ('location', models.CharField(default='', max_length=500)),
                ('no_of_unit_or_plot', models.PositiveSmallIntegerField(default=0)),
                ('price_per_unit_plot', models.CharField(default='', max_length=15)),
                ('on_promo', models.BooleanField(default=False)),
                ('promo_price_per_unit_or_plot', models.CharField(blank=True, default='', max_length=15, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_reward_percentage', models.PositiveSmallIntegerField(blank=True, choices=[(1, '15'), (2, '3')], null=True)),
                ('fifteen_percent_unit', models.PositiveSmallIntegerField(default=0)),
                ('three_percent_unit', models.PositiveSmallIntegerField(default=0)),
                ('realtor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goldapi.Realtor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RealtorClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(default='', max_length=150)),
                ('email', models.CharField(default='', max_length=150, unique=True)),
                ('mobile', models.CharField(default='', max_length=13, unique=True)),
                ('referral_code', models.CharField(default='', max_length=40)),
                ('realtor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goldapi.Realtor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
