# Generated by Django 3.0 on 2022-10-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='mobile',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
