name: Init and Plan

on:
  push:
    branches: [feature/T-1112-terraform-eks]
jobs:
  init_and_plan_terraform:
    name: Init And Plan Terraform
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.version.outputs.date }}
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      - name: Clone GitLab repository
        env:
          GITLAB_ACCESS_TOKEN: ${{ secrets.PAT }}
        run: |
          git clone https://oauth2:${{ secrets.PAT }}@gitlab.com/t4christ/devops-category-two.git
          git checkout feature/T-1112-terraform-eks
          ls devops-category-two && ls devops-category-two/eks-cluster
          # If you want to move the repository to a specific directory, you can use:
          # git clone https://oauth2:${GITLAB_ACCESS_TOKEN}@gitlab.com/<your-gitlab-username>/<your-gitlab-repo>.git <directory-name>

      - name: Initialise Terraform
        run: |
              mkdir ~/.aws && touch ~/.aws/config ~/.aws/credentials
              cat <<EOF > ~/.aws/config
              [profile terraform-ctwo]
              region = us-east-1
              EOF

              cat <<EOF > ~/.aws/credentials
              [terraform-ctwo]
              aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
              EOF

              cd devops-category-two/eks-cluster 
              terraform init
              terraform fmt
              terraform validate
              terraform plan --out eksplan

      - name: Save Plan Output
        id: save-plan
        run: echo "::set-output name=eksplan::$(base64 eksplan)"